# Generated by Django 5.1.5 on 2025-02-13 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_produit_prix'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
