# Generated by Django 5.1.5 on 2025-02-07 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitchentask',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('en_preparation', 'En préparation'), ('prepared', 'Prête')], default='en_attente', max_length=20),
        ),
    ]
