# Generated by Django 5.1.5 on 2025-02-08 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='statut',
            field=models.CharField(choices=[('pending', 'Pending'), ('prepared', 'Prepared'), ('livraison_en_cours', 'Livraison en cours'), ('delivered', 'Delivered')], default='pending', max_length=20),
        ),
    ]
