# Generated by Django 5.1.5 on 2025-02-14 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_commande_statut'),
        ('stock', '0003_produit_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.produit'),
        ),
    ]
