# Generated by Django 5.1.5 on 2025-02-08 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraison', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livraison',
            name='statut',
            field=models.CharField(choices=[('livraison_en_cours', 'Livraison en cours'), ('delivered', 'Delivered')], default='en_cours', max_length=20),
        ),
    ]
